### ISSUE TITLE
Image Excerpt does not automatically store image

### ISSUE THREAD

**Issue by chenhuiapp** [PKM-er/obsidian-zotero#113]
When creating a new literature note, the image excerpt functionality doesn't create the folder if it doesn't exist. Also local picture files are not created, when image excerpts folder is created. 

Local pictures will be created when using the sidebar functionality.

**Comment by aidenlx** [comment]
could you create a minimal vault that can reproduce the issue and upload the zip here in GitHub?

**Comment by aidenlx** [comment]
are you using windows?

**Comment by zhechenghu** [comment]
I would like to report the issue that local picture files are not created when the image excerpts folder is created.

System: MacOS 13.0.1 (22A400)
Obsidian version: v1.1.16

**Comment by MSBack** [comment]
@aidenlx I am having the same issue. When I import a literature note with image excerpts, the file link is inserted according to my settings, but no image is actually created and the link is broken. This is how it looks:
![image](https://github.com/aidenlx/obsidian-zotero/assets/33608083/183de8af-f476-4c59-9432-09305b1cd205)

Note: This happens when using the default image path too.

In the annotation sidepanel, the image also appears broken in some instances, but not always. If I drag and drop using the little handle (see screenshot), the image is not embedded properly.
![image](https://github.com/aidenlx/obsidian-zotero/assets/33608083/ea63d3f0-5237-4b8c-89bf-c974bdd96975)

Dragging directly on the image will work, but doesn't follow the zt-annot.eta template and is simply a typical image paste. See this demo:
![Obsidian_P6O9icnZ2m](https://github.com/aidenlx/obsidian-zotero/assets/33608083/d2d90cdd-484e-4b0a-9bc1-9b3f6a9e4736)

**Comment by MSBack** [comment]
@chenhuiapp I suspect that when you report that dragging from the annotation sidebar works, you are actually dragging on the image itself and not on the drag-and-drop handle, which will format your image embed according to your zt-annot.eta template. See the difference above.

**Comment by MSBack** [comment]
Here's the error log (Log level set to "All") generated when attempting to drag an image excerpt from the annotation sidebar into a note:
```
plugin:obsidian-zotero-plugin:250 Uncaught (in promise) Error: EPERM: operation not permitted, symlink 'D:\Ingmar\Zotero\cache\library\ZXMENH8U.png' -> 'C:\Users\MargitSandberg\Documents\Notir\Obsidian-notir\06 - Resources\ZXMENH8U.png'
await (async)
eval @ plugin:obsidian-zotero-plugin:250
flush @ plugin:obsidian-zotero-plugin:250
eval @ plugin:obsidian-zotero-plugin:249
e.tryTrigger @ app.js:1
e.trigger @ app.js:1
t.trigger @ app.js:1
e.handleDrop @ app.js:1
drop @ app.js:1
e.runCustomHandlers @ app.js:1
n @ app.js:1
(anonymous) @ app.js:1
```

There seems to be a permission issue when the plugin tries to create a symlink between Zotero storage location and the Obsidian image excerpt location.

**Comment by janihr** [comment]
I see a similar behavior as @MSBack describes.

For image excerpts, an annotation with a broken link to the image is created in the literature note. The link is broken as no softlink to the zotero folder is created in the obsidian image excerpt folder.

When I then drag and drop the annotation from the side panel via the handle, all softlinks for all annotations of the current literature note are created.

It seems that for me, the creation of softlinks is just not triggered when creating/updating the literature note.

**Comment by aidenlx** [comment]
should be solved in v1.1.0-beta.4 if you go to Settings and change to "copy" mode
<img width="742" alt="CleanShot 2023-09-04 at 18 10 41@2x" src="https://github.com/PKM-er/obsidian-zotero/assets/31102694/ea106002-f58d-4939-b2b5-96e4f2e57a57">

**Comment by FranzKnut** [comment]
Please excuse me for commenting on an old issue, but I am still facing this problem with Obsidian 1.12.7 and Zotlit 2.0.5!

The console tells me that Zotlit is trying to copy a file from `/home/###/Zotero/cache`. However, I am on mac os so the path to the Zotero cache is actually `/Users/###/Zotero/cache`. 

I am working on this vault from both ubuntu and mac os so I suspect this is the reason for the error.

**Comment by FranzKnut** [comment]
After manually adjusting the fields `zoteroDataDir` and `zoteroCacheDir` in `.obsidian/plugins/zotlit/data.json` I am able to import the image excerpts again. I also tried using a path starting with ~ but without any luck...
